MyProjLol/config/routes.rb
Rails.application.routes.draw do
  get 'company/index' => 'company#index'

  get 'com_man/index' => 'com_man#index'

  get 'signup' => 'users#new'

  #get 'admin/index'

  #get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'govt/index' => 'govt#index'


  resources :users
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  root 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MyProjLol/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyProjLol/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  private

  def confirmation_token
    if confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

MyProjLol/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

MyProjLol/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize
  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Unauthorized User"
    end
  end
end

MyProjLol/app/controllers/com_man_controller.rb
class ComManController < ApplicationController
  def index
  end
end

MyProjLol/app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

MyProjLol/app/controllers/govt_controller.rb
class GovtController < ApplicationController
  def index
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Successfully logged out"
  end
end

MyProjLol/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      if user.email_confirmed
      session[:user_id] = user.id
      case user.user_type
      when 'GOVT'
        redirect_to govt_index_url, notice: "GOVT user's page"
      when 'COMMON-USER'
        redirect_to com_man_index_url, notice: "COMMON user's page"
      when 'PHARMA-COMPANY'
        redirect_to company_index_url, notice: "COMPANY user's page"
      end
      else
        redirect_to login_url, alert: 'Please activate your account by following
the instructions in the account confirmation email you received to proceed'
      end
    else
      redirect_to login_url, alert: 'Invalid user name or password'
    end
  end

  def destroy
    User.find(session[:user_id])
    session[:user_id] = nil
    redirect_to login_url, alert: 'Successfully logged out'
  end
end

MyProjLol/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  # @return [Object]
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_now
        format.html do
          redirect_to login_url, notice: 'User was successfully created.Please confirm your email address to continue'
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html do
          redirect_to login_url, alert: 'Something went wrong!'
        end
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # @return [Object]
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to users_url, notice: 'User was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to the Sample App! Your email has been confirmed.
      Please sign in to continue."
      redirect_to login_url
    else
      flash[:error] = 'Sorry. User does not exist'
      redirect_to root_url
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :user_type, :mobile_number, :email)
  end

end

MyProjLol/app/helpers/admin_helper.rb
module AdminHelper
end

MyProjLol/app/helpers/application_helper.rb
module ApplicationHelper
end

MyProjLol/app/helpers/com_man_helper.rb
module ComManHelper
end

MyProjLol/app/helpers/company_helper.rb
module CompanyHelper
end

MyProjLol/app/helpers/govt_helper.rb
module GovtHelper
end

MyProjLol/app/helpers/sessions_helper.rb
module SessionsHelper
end

MyProjLol/app/helpers/users_helper.rb
module UsersHelper
end

MyProjLol/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

MyProjLol/app/views/com_man/index.html.erb
<div class="container">
  <h2>Common Man</h2>
</div>

<div class="col-md-6">
  <div class="panel with-nav-tabs panel-primary">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
        <li><a href="#water" data-toggle="tab">Water Quality Report</a></li>
        <li><a href="#flood" data-toggle="tab">Flood Detection Report</a></li>
      </ul>
    </div>
    <div class="panel-body">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="water">Water quality report goes here</div>
        <div class="tab-pane fade" id="flood">Flood detection report goes here</div>
      </div>
    </div>
  </div>
</div>

MyProjLol/app/views/company/index.html.erb
<div class="container">
  <h2>Company</h2>
</div>

<div class="col-md-6">
  <div class="panel with-nav-tabs panel-primary">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
        <li><a href="#water" data-toggle="tab">Water Quality Report</a></li>
        <li><a href="#flood" data-toggle="tab">Flood Detection Report</a></li>
      </ul>
    </div>
    <div class="panel-body">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="water">Water quality report goes here</div>
        <div class="tab-pane fade" id="flood">Flood detection report goes here</div>
      </div>
    </div>
  </div>
</div>

MyProjLol/app/views/govt/index.html.erb
<div class="container">
  <h2>Government</h2>
</div>

<div class="col-md-6">
  <div class="panel with-nav-tabs panel-primary">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
        <li><a href="#water" data-toggle="tab">Water Quality Report</a></li>
        <li><a href="#flood" data-toggle="tab">Flood Detection Report</a></li>
      </ul>
    </div>
    <div class="panel-body">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="water">Water quality report goes here</div>
        <div class="tab-pane fade" id="flood">Flood detection report goes here</div>
      </div>
    </div>
  </div>
</div>

MyProjLol/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Water Monitoring and Flood Detection Report</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
<header id="header" class="water-navbar navbar">
  <h1>Water Monitoring and Flood Detection Report</h1>
  <%=	 link_to "Log out", logout_url, { :style => "color :white" }%>
</header>
<div class="container">
  <div class="container-fluid">
    <div id="water-body">
      <% if flash[:notice]  %>
        <div role="alert" class="alert alert-success alert-dismissible fade show">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% if flash[:alert]  %>
        <div role="alert" class="alert alert-danger alert-dismissible fade show">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

<footer id="footer" class="water-footer">
    <p>footer</p>
</footer>
</body>
</html>

MyProjLol/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <fieldset>
    <legend>Create Account</legend>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, :class => 'form-control' %>
    </div>
  </div>

  <div class="field">
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, :class => 'form-control' %>
  </div>
  </div>

  <div class="field">
    <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation, :class => 'form-control' %>
  </div>
  </div>

  <div class="field">
    <div  class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, :class => 'form-control' %>
  </div>
  </div>

    <div class="field">
      <div  class="form-group">
        <%= form.label :mobile_number %>
        <%= form.number_field :mobile_number, id: :user_mobile_number, :class => 'form-control' %>
      </div>
    </div>

  <div class="field">
    <div class="form-group">
    <%= form.label :user_type%>
      <%= form.select :user_type, options_for_select([%w(GOVT GOVT), %w(PHARAMA-COMPANY PHARMA-COMPANY),
                                                      %w(COMMON-USER COMMON-USER), %w(ADMIN ADMIN)]), {include_blank: "Select Type"}, {:class => 'form-control' }  %>
    </div>
  </div>

  <%= form.submit :class => 'btn btn-primary'%>
  </fieldset>
<% end %>

MyProjLol/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

MyProjLol/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', login_url %>

MyProjLol/app/views/users/new.html.erb
<div class="row">
<div class="col-md-4"></div>
<div class="col-md-4">
<%= render 'form', user: @user %>
<br/>
<span> Already have an account? Go to </span>
<%= link_to 'Login Page', login_url %>
</div>
<div class="col-md-4"></div>
</div>

MyProjLol/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>